#!/usr/bin/env groovy
pipeline{
    agent none
    stages {
        stage('bild'){
            agent{
                docker { image 'maven' }
            }
            steps {
                sh "mvn spring-boot:run"
            }
        }
    }
}